### ISSUE TITLE
I've met some trouble in using megengine

### ISSUE THREAD

**Issue by fffire-oss** [MegEngine/FINet#3]
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    train_proc(params)
  File "train.py", line 136, in main
    train_and_evaluate(model, manager)
  File "train.py", line 92, in train_and_evaluate
    train(model, manager, gm)
  File "train.py", line 56, in train
    gm.backward(loss["total"])
  File "/home/jzf/anaconda3/envs/meg/lib/python3.7/site-packages/megengine/autodiff/grad_manager.py", line 289, in backward
    self._grad(ys, dys)
  File "/home/jzf/anaconda3/envs/meg/lib/python3.7/site-packages/megengine/core/autodiff/grad.py", line 67, in __call__
    self._impl.backward(ys, dys)
  File "/home/jzf/anaconda3/envs/meg/lib/python3.7/site-packages/megengine/core/autodiff/grad.py", line 20, in backward
    return core2.backward(self, ys, dys)
RuntimeError: assertion `val.shape().is_scalar()' failed at ../../../../../../src/opr/impl/tensor_manip.cpp:1011: bool mgb::opr::Split::infer_shape(size_t, megdnn::TensorShape&, const mgb::cg::static_infer::InpVal&)
extra message: shapes for Split must be scalars

**Comment by fffire-oss** [comment]
I use MegEngine of the latest version==1.11.0

**Comment by hxwork** [comment]
Hi,

Thanks for your interest! I am sorry that I only tested my code using MegEngine==1.7.0. Maybe downgrading the MegEngine version can solve your problem.

Best regards,
Hao

**Comment by xaioqi16** [comment]
I encountered the same problem, how did you solve it

**Comment by xaioqi16** [comment]
I encountered the same problem, how did you solve it

**Comment by xaioqi16** [comment]
I encountered the same problem, how did you solve it

**Comment by hxwork** [comment]
Hi,

Have you tried to downgrade the MegEngine? Another workaround is using the Pytorch version of our work, please refer to [this repo](https://github.com/hxwork/FINet_Pytorch).

**Comment by xaioqi16** [comment]
Thanks for your suggestion, I'm trying the pytorch version.
